package com.zugaldia.stargate.app

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull
import kotlin.test.assertTrue

class AppUtilsTest {

    @Test
    fun `unicodeToKeySym and keySymToUnicode round-trip for plain English`() {
        val input = "Using my voice, I can type at the speed of sound."
        for (char in input) {
            val keySym = unicodeToKeySym(char.code)
            val roundTripped = keySymToUnicode(keySym)
            val codeHex = char.code.toString(16).uppercase()
            assertEquals(char.code, roundTripped, "Round-trip failed for '$char' (U+$codeHex)")
        }
    }

    // The sample files contain Article 1 of the Universal Declaration of Human Rights in all six
    // official languages of the UN: English, French, Spanish, Russian, Arabic, and Chinese.
    // They are generated by the Makefile in the resources directory from the official UN website (un.org).
    private fun loadAllSamples(): String {
        val sampleFiles = SAMPLE_LANGUAGES.mapNotNull { it.second }
        return sampleFiles.joinToString("\n") { filename ->
            val resource = javaClass.classLoader.getResourceAsStream(filename)
            assertNotNull(resource, "$filename not found in resources")
            resource.bufferedReader(Charsets.UTF_8).readText()
        }
    }

    @Test
    fun `textToKeySym succeeds for plain English`() {
        val input = "Using my voice, I can type at the speed of sound."
        val result = textToKeySym(input)
        assertEquals(input.length, result.size)
    }

    @Test
    fun `textToKeySym succeeds for all languages in samples`() {
        val sample = loadAllSamples()
        val result = textToKeySym(sample)
        assertTrue(result.isNotEmpty())
    }

    @Test
    fun `unicodeToKeySym and keySymToUnicode round-trip for all characters in samples`() {
        val sample = loadAllSamples()
        for (char in sample) {
            val keySym = unicodeToKeySym(char.code)
            val roundTripped = keySymToUnicode(keySym)
            val codeHex = char.code.toString(16).uppercase()
            assertEquals(char.code, roundTripped, "Round-trip failed for '$char' (U+$codeHex)")
        }
    }
}
